name: run-tests
on: [push]
jobs:
  resume-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g resume-cli
      - run: npm install
      - run: resume test
